### PR TITLE
Add project based west.yml

### LINKED ISSUE #22: Improving west.yml support when using framework-zephyr
Hi, 

I would like to propose changes to scripts located inside `framework-zephyr` but I understood that they were not on git yet. 
Is it possible to have a separate issue tracker for `framework-zephyr` pio scripts (namely `install-deps.py` `platformio-build.py` and `platformio-pre-build.py` ? 

**Problem statement :** 

In the current implementation zephyr dependencies are installed by parsing and downloading entries in main `west.yml` file in `framework-zephyr` folder. Installed dependencies version numbers are stored in `state.json` in `_pio` folder. 

I found two improvements that should be relatively easy to implement (I can propose a PR if there is a git for these files)

1) Fix the way `install-deps.py` check if dependency should be installed or not. At the moment even if version number is stored in `state.json`, the only thing triggering download action is the presence (or the absence) of the module folder in `_pio` directory, no matter if the version has changed. Then no matter what, `state.json` is updated with new version hash, without upgrading the module itself. 
Currently, the only way of changing the version of a dependency is to manually edit `west.yml` then to supress corresponding module folder to trigger module install.

2) In zephyr workflow, user can have a project based `west.yml` file that permits to have per project dependencies. This is currently not the case in platformio, where `west.yml` is not meant to be modified by the user.  
**Proposed change is :**
- Add a path to a local `west.yml` in `platformio-build.py` using `PROJECT_DIR`
- Check presence of a potential `west.yml` in the project folder, if so, feed this file path to the `install-deps.py` python cmd. (in function `load_west_manifest()`)
- Add a script argument in `main` of `install-deps.py` to retrieve correctly west.yml path. 
- Feed correct path to `get_cmake_code_model()` 

What do you think ?

### PR DESCRIPTION
**Pull request by jalinei**
- [x] Modules version stored in state.json now correctly compared with west.yml revision hash
- [x] Add the possibility to provide dependencies through a project based west.yml file. 
- [ ] Add the possibility to skip large installation times due to default west.yml

Fixes #22 
Tested on Ubuntu 20.04, I don't have access to a Windows machine to check classic curses.. 

Questions from my side : 
- I guess I should add the same workaround in `clear_deprecated_package` than in `clean_up` to wipe `.git` folder on windows machines ? I can add that commit when confirmed. 
- Is it really necessary to have `install-deps.py` script called from tool manager ? With the current logic, there is no way to skip the initial download, that encompass all packages defined in framework based `west.yml` which leads to unnecessary disk space occupation & installation times. 
(Example in Ststm32 platform : https://github.com/platformio/platform-ststm32/blob/develop/platform.py#L124)

My proposal would be to launch `install-deps.py` only from `platformio-build.py`, this way a potential local west.yml can be detected and install time can be dramatically reduced (from 3GB+ to approx 600MB in our case).

Opinion : 
- I don't really understand the added value of --secondary-installation parameter. I got that it permits to distinguish if script is launched from tool-manager or by `platformio-build.py` but in practice it does not change much.

### CODE REVIEW

**Comment by jalinei** [comment]
@valeros did you have time to get an eye on this one ? :smiley:

**Comment by valeros** [comment]
Hi @jalinei, sorry for the delay, I'll look into the PR soon. In the meantime, could you please put together a few projects to properly test out this new functionality? I'm especially interested in more advanced examples that involve project-specific `west.yml` that partially overrides the default one.

**Comment by jalinei** [comment]
My test branch is that one : https://github.com/jalinei/Core/tree/test_west

- it can't compile without downloading dependencies from thingset that are not present in regular west.yml. 
- it has a specific version of zcbor that differs from regular west.yml (to test that after a default install, version is now correctly compared using state.json (can also be tested by forcing another hash version in state.json)
- it has a forked hal to showcase how much we could shrunk the dependencies (only shipping stm32g4xx) for our specific case. Not working yet, because install-deps is still launched from project agnostic main `platform.py` so non expert user will still download default modules

**Comment by valeros** [comment]
Thanks, added.

**Pull request merged**
